- name: "downloadbin {{ db__opts_name }} | Ensure bin directory"
  file:
    path: "{{ db__opts_bin_dir }}"
    state: directory
    mode: "0755"
    owner: root

- name: "downloadbin {{ db__opts_name }} | Ensure archive directory"
  file:
    path: "{{ db__opts_archive_dir }}"
    state: directory
    mode: "0755"
    owner: root
  when: db__opts_archived

- name: "downloadbin {{ db__opts_name }} | Check downloaded"
  stat:
    path: "{{ db__download_dest }}"
  register: db__download_stats

- name: "downloadbin {{ db__opts_name }} | Download"
  get_url:
    url: "{{ db__opts_url }}"
    dest: "{{ db__download_dest }}"
    force: yes
    mode: "{{ db__opts_mode }}"
    checksum: "sha1:{{ db__opts_sha1 }}"
  when: not(db__download_stats.stat.checksum is defined and db__download_stats.stat.checksum == db__opts_sha1)
  notify: "{{ db__opts_notify }}"

- name: "downloadbin {{ db__opts_name }} | Extract"
  unarchive:
    src: "{{ db__download_dest }}"
    dest: "{{ db__opts_bin_dir }}"
    remote_src: yes
    extra_opts: "{{ db__opts_unarchive_extra_opts }}"
  when: db__opts_archived

- name: "downloadbin {{ db__opts_name }} | setcap"
  command: "setcap {{ db__opts_bin_setcap }} {{ db__opts_bin_path }}"
  when: db__opts_bin_setcap != ""

- name: "downloadbin {{ db__opts_name }} | Link binary"
  file:
    src: "{{ db__opts_bin_path }}"
    dest: "{{ db__opts_link_dest }}/{{ db__opts_link_name }}"
    state: link
  when: not((db__opts_link_dest | trim == "") or (db__opts_link_dest is none))
